version: "3"
services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: SuperSecret!23
    volumes:
      - .docker-data/postgres:/var/lib/postgresql/data